// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Le migrazioni usano una connessione DIRETTA (non poolata).
    // Con Neon: DIRECT_URL = stringa diretta, DATABASE_URL = stringa "pooled".
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
